#!/bin/bash

INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
QUEUE=`aws --region=eu-west-1 ec2 describe-tags --filters "Name=resource-id,Values=i-4550f805" "Name=key,Values=sourcequeue" | jq -r '.Tags[].Value'`
BUCKET=`aws --region=eu-west-1 ec2 describe-tags --filters "Name=resource-id,Values=i-4550f805" "Name=key,Values=targetbucket" | jq -r '.Tags[].Value'`

while true
do
MESSAGE=`aws --region=eu-west-1 sqs receive-message --queue-url=$QUEUE | jq -r '.Messages[].Body'`
MD5=`echo $MESSAGE | md5sum | awk '{print $1}'`
COW=`echo $MESSAGE | cowsay`

cat << EOF > $MD5.html
<html>
<body>
<pre>
$COW
</pre>
</body>
</html>
EOF

aws --region=eu-west-1 s3 cp $MD5.html s3://$BUCKET
sleep 1
done
